- hosts: localhost
  vars:
      ansible_python_interpreter: /home/chuck/Desktop/Projects/nexus/venv/bin/python3
  tasks:

    - name: download nexus
      get_url:
        url: http://download.sonatype.com/nexus/3/nexus-3.22.0-02-unix.tar.gz
        dest: /opt
    - name: Untar nexus
      unarchive:
        src: /opt/nexus-3.22.0-02-unix.tar.gz
        dest: /opt/
    - name: add group
      group:
        name: nexus
        state: present
    - name: add user 
      user:
        name: nexus
        password: "{{ nexus | password_hash('sha512') }}"
        state: present
    - name: permission setup
      file:
        dest: "{{ item }}"
        owner: nexus
        group: nexus
        recurse: yes
      with_items:
        - /opt/nexus-3.22.0-02
        - /opt/sonatype-work
    - name: set nexus.rc file
      copy:
        src: nexus.rc
        dest: /opt/nexus-3.22.0-02/bin/nexus.rc
        owner: nexus
        group: nexus
    - name: copy nexus vm options
      copy:
        src: nexus.vmoptions
        dest: /opt/nexus-3.22.0-02/bin/nexus.vmoptions
        owner: nexus
        group: nexus
    - name: setup service file
      copy:
        src: nexus.service
        dest: /etc/systemd/system/nexus.service
    - name: start service
      service:
        name: nexus
        state: started
        enabled: yes

      
    